root: true

env:
  node: true
  es2020: true

parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"

ignorePatterns:
  - "dist/"

rules:
  "@typescript-eslint/no-unused-vars": warn
  "@typescript-eslint/no-explicit-any": off